services:
  - type: web
    name: hay-fever-management
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
